// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "./src/models",
  migrations: {
    path: "./src/database/migrations",
    seed: "npx ts-node ./src/database/seeders/seed.ts",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
